# Sử dụng image Python cơ bản
FROM python:3.10-slim

# Cài đặt FFmpeg (rất quan trọng)
# Cập nhật và cài đặt các gói cần thiết, bao gồm ffmpeg
RUN apt-get update && \
    apt-get install -y ffmpeg netcat-openbsd && \
    rm -rf /var/lib/apt/lists/*

# Thiết lập thư mục làm việc
WORKDIR /app

# COPY ../scripts/simulateRTSP.py /app/simulateRTSP.py
RUN pip install --no-cache-dir natsort requests


# Lệnh mặc định sẽ chạy script start
CMD ["python", "simulateRTSP.py", "start"]