# Sử dụng image Python cơ bản
FROM python:3.10-slim

# Cài đặt FFmpeg (rất quan trọng)
# Cập nhật và cài đặt các gói cần thiết, bao gồm ffmpeg
RUN apt-get update && \
    apt-get install -y ffmpeg netcat-openbsd && \
    rm -rf /var/lib/apt/lists/*

# Thiết lập thư mục làm việc
WORKDIR /app

COPY ../scripts/simulate_rtsp_streams.py /app/simulate_rtsp_streams.py


# Lệnh mặc định sẽ chạy script start
CMD ["python", "simulate_rtsp_streams.py", "start"]